#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/past_questions.csv から index.html が読み込む chintaikanrishi-master-data.js を生成する。"""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_CSV = ROOT / "data" / "past_questions.csv"
OUT_JS = ROOT / "chintaikanrishi-master-data.js"

LABELS = [("ア", "statement_a"), ("イ", "statement_b"), ("ウ", "statement_c"), ("エ", "statement_d")]


def norm(s: str | None) -> str:
    return (s or "").strip()


def parse_correct(raw: str) -> int | None:
    raw = norm(raw)
    if not raw:
        return None
    try:
        n = int(raw)
    except ValueError:
        return None
    if 1 <= n <= 4:
        return n
    return None


def build_stem_html(row: dict) -> str:
    parts: list[str] = []
    stem = norm(row.get("stem"))
    preamble = norm(row.get("preamble"))
    if stem:
        parts.append(f"<p>{_esc(stem).replace(chr(10), '<br>')}</p>")
    if preamble:
        parts.append(f"<p>{_esc(preamble).replace(chr(10), '<br>')}</p>")
    stmts: list[tuple[str, str]] = []
    for lab, key in LABELS:
        t = norm(row.get(key))
        if t:
            stmts.append((lab, t))
    if stmts:
        lis = "".join(f"<li><strong>{lab}</strong> {_esc(t).replace(chr(10), '<br>')}</li>" for lab, t in stmts)
        parts.append(f"<ol class=\"q-stmt-list\" style=\"list-style:none;padding-left:0;\">{lis}</ol>")
    return "\n".join(parts) if parts else "<p>（問題文なし）</p>"


def _esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def row_to_obj(row: dict, line_no: int) -> dict:
    year = int(row["exam_year"])
    qno = int(row["question_no"])
    opts = [norm(row.get(f"choice_{i}")) for i in range(1, 5)]
    if not all(opts):
        raise ValueError(f"line {line_no}: 選択肢欠け year={year} no={qno}")
    inv = norm(row.get("is_invalidated", "")).upper() == "TRUE"
    cor = parse_correct(row.get("correct"))
    if cor is None and not inv:
        raise ValueError(f"line {line_no}: 正答なし year={year} no={qno}")
    return {
        "id": f"past-{year}-{qno:02d}",
        "examYear": year,
        "examWareki": norm(row.get("exam_wareki")),
        "questionNo": qno,
        "type": norm(row.get("type")) or "single",
        "category": norm(row.get("category")),
        "tags": norm(row.get("tags")),
        "stemHtml": build_stem_html(row),
        "choices": opts,
        "correct": cor,
        "isExempt": norm(row.get("is_exempt", "")).upper() == "TRUE",
        "isInvalidated": inv,
        "note": norm(row.get("note")),
        "explanation": norm(row.get("explanation")) or "（解説は未入力です。）",
    }


def main() -> int:
    if not DATA_CSV.is_file():
        print(f"入力がありません: {DATA_CSV}", file=sys.stderr)
        return 1
    text = DATA_CSV.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    objs: list[dict] = []
    for i, row in enumerate(rows, start=2):
        objs.append(row_to_obj(row, i))
    js = (
        "// auto-generated by tools/csv_to_chintaikanrishi_data.py — do not edit by hand\n"
        "var CHINTAIKANRISHI_QUESTIONS = "
        + json.dumps(objs, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT_JS} ({len(objs)} questions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
