#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/past_questions_marubatsu_all_explanations.csv → eisei1-data-ichimon.js（window.ICHI_MON_ROWS）。

CSV 列: id, question, answer, explanation, category, tags, source, note
- answer: ○＝記述が正しい / ×＝記述が誤り（index.html の correctAnswer と一致）
- category: tools/csv_to_chintaikan_eisei_master.py の CATEGORY_TO_FIELD と揃える
"""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_CSV = ROOT / "data" / "past_questions_marubatsu_all_explanations.csv"
OUT_JS = ROOT / "eisei1-data-ichimon.js"

# index.html の FIELDS id（law / rights / limit）— csv_to_chintaikan_eisei_master と同一＋不足分
CATEGORY_TO_FIELD: dict[str, str] = {
    "賃貸住宅管理業法": "law",
    "関連法令": "law",
    "賃貸不動産経営": "law",
    "政策課題・社会情勢": "law",
    "賃貸借契約": "rights",
    "賃貸借契約実務": "rights",
    "民法・借地借家法": "rights",
    "賃料管理・督促": "rights",
    "原状回復": "rights",
    "サブリース": "rights",
    "管理実務": "rights",
    "建物・設備": "limit",
    "会計・税金・保険": "limit",
    "会計税務": "limit",
}

_ID_PATH = re.compile(r"^(\d{4})-(\d+)-(\d+)$")


def norm(s: str | None) -> str:
    return (s or "").strip()


def category_to_field(cat: str) -> str:
    c = norm(cat)
    f = CATEGORY_TO_FIELD.get(c)
    if not f:
        raise ValueError(f"未対応の category={c!r}")
    return f


def parse_marubatsu_answer(raw: str) -> bool:
    """True = 記述は正しい（ユーザー正解は○） / False = 記述は誤り（正解は×）"""
    s = norm(raw)
    if s in ("○", "〇"):
        return True
    if s in ("×", "✕", "╳"):
        return False
    raise ValueError(f"想定外の answer 列: {raw!r}")


def public_path_from_id(row_id: str) -> str:
    m = _ID_PATH.match(norm(row_id))
    if not m:
        return ""
    y, qn, _ = m.groups()
    return f"q/past/y{int(y)}/q{int(qn):02d}/index.html"


def normalize_statement(text: str) -> str:
    s = norm(text).replace("\r\n", "\n").replace("\r", "\n")
    s = re.sub(r"\s+", " ", s)
    return s


def row_to_obj(row: dict, line_no: int) -> dict:
    rid = norm(row.get("id"))
    if not rid:
        raise ValueError(f"line {line_no}: id が空です")
    cat = norm(row.get("category"))
    return {
        "id": rid,
        "field": category_to_field(cat),
        "statement": normalize_statement(norm(row.get("question"))),
        "correctAnswer": parse_marubatsu_answer(norm(row.get("answer"))),
        "exp": norm(row.get("explanation")) or "（解説は未入力です。）",
        "publicPath": public_path_from_id(rid),
    }


def main() -> int:
    if not DATA_CSV.is_file():
        print(f"入力がありません: {DATA_CSV}", file=sys.stderr)
        return 1
    text = DATA_CSV.read_text(encoding="utf-8-sig")
    rows_in = list(csv.DictReader(text.splitlines()))
    objs: list[dict] = []
    for i, row in enumerate(rows_in, start=2):
        objs.append(row_to_obj(row, i))

    payload = json.dumps(objs, ensure_ascii=False, indent=2)
    js = (
        "/* AUTO-GENERATED by tools/csv_to_eisei_ichimon_js.py — data/past_questions_marubatsu_all_explanations.csv を編集して再実行 */\n"
        f"window.ICHI_MON_ROWS = {payload};\n"
    )
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT_JS} ({len(objs)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
