#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/past_questions.csv → eisei1shu 互換の eisei1-master-data.js（CSV_IMPORTED_*）を生成する。"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_CSV = ROOT / "data" / "past_questions.csv"
OUT_JS = ROOT / "eisei1-master-data.js"

LABELS = [("ア", "statement_a"), ("イ", "statement_b"), ("ウ", "statement_c"), ("エ", "statement_d")]

# index.html の FIELDS id（law / rights / limit）に対応
CATEGORY_TO_FIELD: dict[str, str] = {
    "賃貸住宅管理業法": "law",
    "関連法令": "law",
    "賃貸不動産経営": "law",
    "政策課題・社会情勢": "law",
    "賃貸借契約": "rights",
    "賃貸借契約実務": "rights",
    "民法・借地借家法": "rights",
    "賃料管理・督促": "rights",
    "原状回復": "rights",
    "サブリース": "rights",
    "管理実務": "rights",
    "建物・設備": "limit",
    "会計・税金・保険": "limit",
    "会計税務": "limit",
}


def norm(s: str | None) -> str:
    return (s or "").strip()


def build_plain_text(row: dict) -> str:
    parts: list[str] = []
    stem = norm(row.get("stem"))
    preamble = norm(row.get("preamble"))
    if stem:
        parts.append(stem)
    if preamble:
        parts.append(preamble)
    for lab, key in LABELS:
        t = norm(row.get(key))
        if t:
            parts.append(f"{lab}　{t}")
    return "\n\n".join(parts) if parts else "（問題文なし）"


def parse_correct(raw: str) -> int | None:
    raw = norm(raw)
    if not raw:
        return None
    try:
        n = int(raw)
    except ValueError:
        return None
    if 1 <= n <= 4:
        return n - 1
    return None


def row_to_obj(row: dict, line_no: int) -> dict | None:
    if norm(row.get("is_invalidated", "")).upper() == "TRUE":
        return None
    year = int(row["exam_year"])
    qno = int(row["question_no"])
    cat = norm(row.get("category"))
    field = CATEGORY_TO_FIELD.get(cat)
    if not field:
        raise ValueError(f"line {line_no}: 未対応の category={cat!r}")

    opts = [norm(row.get(f"choice_{i}")) for i in range(1, 5)]
    if not all(opts):
        raise ValueError(f"line {line_no}: 選択肢欠け year={year} no={qno}")

    inv = norm(row.get("is_invalidated", "")).upper() == "TRUE"
    cor = parse_correct(row.get("correct"))
    if cor is None and not inv:
        raise ValueError(f"line {line_no}: 正答なし year={year} no={qno}")

    text = build_plain_text(row)
    exp = norm(row.get("explanation")) or "（解説は未入力です。）"

    qid = year * 100 + qno
    return {
        "id": qid,
        "year": year,
        "num": qno,
        "field": field,
        "text": text,
        "opts": opts,
        "ans": 0 if cor is None else cor,
        "exp": exp,
    }


def main() -> int:
    if not DATA_CSV.is_file():
        print(f"入力がありません: {DATA_CSV}", file=sys.stderr)
        return 1
    text = DATA_CSV.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    objs: list[dict] = []
    year_labels: dict[int, str] = {}
    for i, row in enumerate(rows, start=2):
        o = row_to_obj(row, i)
        if o is None:
            continue
        objs.append(o)
        y = o["year"]
        wl = norm(row.get("exam_wareki"))
        if y not in year_labels and wl:
            year_labels[y] = f"{wl}（{y}年）"

    lines = [
        "// AUTO-GENERATED by tools/csv_to_chintaikan_eisei_master.py — data/past_questions.csv を編集し再生成",
        "const CSV_IMPORTED_YEAR_LABELS = " + json.dumps(year_labels, ensure_ascii=False) + ";",
        "const CSV_IMPORTED_ORIG_POOL_YEARS = [];",
        "const CSV_IMPORTED_QUESTIONS = [",
    ]
    for o in objs:
        lines.append("  " + json.dumps(o, ensure_ascii=False) + ",")
    lines.append("];")
    lines.append("")
    lines.append("if (typeof applyCsvImportedQuestions === 'function') {")
    lines.append("  applyCsvImportedQuestions();")
    lines.append("}")
    lines.append("")

    OUT_JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_JS} ({len(objs)} questions, {len(year_labels)} year labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
